gaepdit/complaint-tracking

- ComplaintTracking/ComplaintTracking.csproj
> Uprade to .NET 5

- ComplaintTracking/ComplaintTracking.csproj
- ComplaintTracking/Controllers/ReportsController.cs
- ComplaintTracking/ViewModels/ReportViewModels/ReportDaysSinceLastActionByStaffViewModel.cs
- ComplaintTracking/Views/Reports/DaysSinceLastActionByStaff.cshtml
- ComplaintTracking/Views/Reports/Index.cshtml
> Create a new report

- ComplaintTracking/Views/Account/ChangePassword.cshtml
- ComplaintTracking/Views/Account/ForgotPassword.cshtml
- ComplaintTracking/Views/Account/Login.cshtml
- ComplaintTracking/Views/Account/ResetPassword.cshtml
- ComplaintTracking/Views/Account/SetPassword.cshtml
- ComplaintTracking/Views/Shared/_PasswordRequirementsPartial.cshtml
- ComplaintTracking/web.config
Adds a redirect for `.well-known/change-password` and adds `autocomplete` attributes to username/password fields.
closes #490
> Improve password manager compatibility

- ComplaintTracking/DAL/DAL.Complaints.cs
- ComplaintTracking/Data/SeedTestData/ComplaintTestData.cs
- ComplaintTracking/Data/SeedTestData/ComplaintTransitionTestData.cs
- ComplaintTracking/Models/Complaint.cs
- ComplaintTracking/ViewModels/ComplaintViewModels/SearchComplaintsViewModel.cs
- DB Objects/gora.ClosedComplaintActions.sql
- DB Objects/gora.OpenComplaints.sql
A new complaint status is added -- "Administratively Closed" -- and new complaint search options are added.
closes #488
> Add ability to track administratively closed complaints

- ComplaintTracking/Controllers/ComplaintsController.Search.cs
- ComplaintTracking/Controllers/PublicController.cs
- ComplaintTracking/DAL/DAL.Complaints.cs
- ComplaintTracking/Data/MigratorHostedService.cs
- ComplaintTracking/Helpers/DataExport.cs
- ComplaintTracking/Startup.cs
- ComplaintTracking/ViewModels/ComplaintViewModels/ComplaintListViewModel.cs
- ComplaintTracking/ViewModels/ComplaintViewModels/SearchResultsExportViewModel.cs
- ComplaintTracking/ViewModels/ComplaintViewModels/SearchResultsWithDeleteExportViewModel.cs
- ComplaintTracking/ViewModels/PublicViewModels/PublicSearchResultsViewModel.cs
- ComplaintTracking/Views/Complaints/Index.cshtml
- ComplaintTracking/Views/Public/Index.cshtml
> Add additional columns to CTS search results

- ComplaintTracking/ComplaintTracking.csproj
> Update target framework to .NET 6 and update NuGet packages

- ComplaintTracking/Controllers/UsersController.cs
Previous method did not include lowercase letters
fixes #510
> Generate compliant temporary password

- ComplaintTracking/Views/Shared/_Layout.cshtml
- ComplaintTracking/Views/Shared/_StandardStylesheetsPartial.cshtml
- ComplaintTracking/wwwroot/assets/css/site.css
> Remove obsolete GeorgiaGov branding

- ComplaintTracking/Helpers/SecurityHeaders.cs
> Fix Reporting API

- ComplaintTracking/Helpers/SecurityHeaders.cs
- ComplaintTracking/Views/Complaints/Details.cshtml
- ComplaintTracking/Views/Public/ComplaintDetails.cshtml
> Fix recent CSP violations

- ComplaintTracking/Controllers/ComplaintsController.Transitions.cs
- ComplaintTracking/Controllers/ComplaintsController.View.cs
> Prevent accepting a complaint that has been submitted for review

- ComplaintTracking/Controllers/ComplaintActionsController.cs
- ComplaintTracking/DAL/DAL.ComplaintActions.cs
- ComplaintTracking/ViewModels/ComplaintActionViewModels/SearchComplaintActionsViewModel.cs
- ComplaintTracking/Views/ComplaintActions/Index.cshtml
> Enable searching complaint actions by concern

- ComplaintTracking/ComplaintTracking.csproj
- ComplaintTracking/wwwroot/.well-known/security.txt
updated csproj file, added security.txt in .well-known in wwwroot
> updating csproj file, added security.txt in .well-known in wwwroot

- ComplaintTracking/wwwroot/.well-known/security.txt
fixed policy link to correct github security policy link
> Correct Policy Link

- ComplaintTracking/Views/Shared/_FaviconPartial.cshtml
Favicon background: https://github.com/gaepdit/gaepd-brand/pull/7 and https://github.com/gaepdit/EPD-IT/issues/126
> Update favicon code

- .github/workflows/sonarcloud-scan.yml
- Directory.Packages.props
- global.json
- src/AppServices/AppServices.csproj
- src/AppServices/Staff/CurrentUserNotFoundException.cs
- src/Domain/Domain.csproj
- src/Domain/Exceptions/InvalidFileTypeException.cs
- src/Domain/Exceptions/NameAlreadyExistsException.cs
- src/EfRepository/Contexts/AppDbContextFactory.cs
- src/EfRepository/EfRepository.csproj
- src/LocalRepository/LocalRepository.csproj
- src/TestData/TestData.csproj
- src/WebApp/Platform/Services/DataStores.cs
- src/WebApp/Platform/Services/MigratorHostedService.cs
- src/WebApp/WebApp.csproj
- tests/AppServicesTests/AppServicesTests.csproj
- tests/DomainTests/DomainTests.csproj
- tests/EfRepositoryTests/EfRepositoryTests.csproj
- tests/EfRepositoryTests/RepositoryHelper.cs
- tests/LocalRepositoryTests/LocalRepositoryTests.csproj
- tests/WebAppTests/WebAppTests.csproj
ref: https://github.com/gaepdit/EPD-IT/issues/127
> Update vNext to .NET 8

- .github/workflows/codeql-analysis.yml
- ComplaintTracking/ComplaintTracking.csproj
- ComplaintTracking/appsettings.json
- global.json
ref: https://github.com/gaepdit/EPD-IT/issues/127
> Upgrade main to .NET 8

- ComplaintTracking/Properties/PublishProfiles/azure-dev-app.pubxml
- ComplaintTracking/Properties/PublishProfiles/azure-prod-app-1.pubxml
- ComplaintTracking/Properties/PublishProfiles/azure-prod-app-2.pubxml
- ComplaintTracking/Properties/PublishProfiles/azure-test-app.pubxml
ref: https://github.com/gaepdit/EPD-IT/issues/129
> Add Azure publish profiles

- ComplaintTracking/Services/CtsAttachmentService.cs
**DO NOT MERGE OR DEPLOY UNTIL ALL PHYSICAL FILES ARE MOVED!!!**
This PR changes the attachment service to split attachment and image thumbnail storage into folders named after the first two characters in the file ID (which is a GUID plus file extension). This is the scheme used by both Git and 1Password.
See [file - Using GUID's as folder names + splitting up - Stack Overflow](https://stackoverflow.com/questions/13841931/using-guids-as-folder-names-splitting-up) for a related discussion.
All existing files must be moved into their correct subfolders when deploying. This can most easily be accomplished by combining the effort with #651 which already requires moving the files.
> Split up Attachments into subfolders

- src/AppServices/Complaints/ComplaintService.cs
- src/AppServices/Complaints/Dto/ComplaintViewDto.cs
- src/AppServices/Complaints/IComplaintService.cs
- src/Domain/Entities/Complaints/IComplaintRepository.cs
- src/EfRepository/Repositories/ComplaintRepository.cs
- src/LocalRepository/Repositories/LocalComplaintRepository.cs
- src/WebApp/Pages/Shared/_Layout.cshtml
- src/WebApp/Pages/Staff/Complaints/Delete.cshtml
- src/WebApp/Pages/Staff/Complaints/Delete.cshtml.cs
- src/WebApp/Pages/Staff/Complaints/DeleteAction.cshtml
- src/WebApp/Pages/Staff/Complaints/Details.cshtml
- src/WebApp/Pages/Staff/Complaints/Restore.cshtml
- src/WebApp/Pages/Staff/Complaints/Restore.cshtml.cs
- src/WebApp/Pages/Staff/Complaints/RestoreAction.cshtml
- src/WebApp/wwwroot/css/site.css
- tests/AppServicesTests/Complaints/Find.cs
- tests/AppServicesTests/Complaints/FindPublic.cs
This PR implements delete and restore for complaints.
Also, the buttons on the complaint details page have been rearranged slightly.
> Implement complaint delete and restore

- src/WebApp/Pages/Account/Edit.cshtml
- src/WebApp/Pages/Account/Login.cshtml
- src/WebApp/Pages/Admin/Maintenance/ActionTypes/Add.cshtml
- src/WebApp/Pages/Admin/Maintenance/ActionTypes/Edit.cshtml
- src/WebApp/Pages/Admin/Maintenance/Concerns/Add.cshtml
- src/WebApp/Pages/Admin/Maintenance/Concerns/Edit.cshtml
- src/WebApp/Pages/Admin/Maintenance/Offices/Add.cshtml
- src/WebApp/Pages/Admin/Maintenance/Offices/Edit.cshtml
- src/WebApp/Pages/Admin/Users/Edit.cshtml
- src/WebApp/Pages/Admin/Users/EditRoles.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/ValidationSummaryConditional.cshtml
- src/WebApp/Pages/Shared/_AlertPartial.cshtml
- src/WebApp/Pages/Staff/ComplaintActions/Edit.cshtml
- src/WebApp/Pages/Staff/Complaints/Add.cshtml
- src/WebApp/Pages/Staff/Complaints/Assign.cshtml
- src/WebApp/Pages/Staff/Complaints/Details.cshtml
- src/WebApp/Pages/Staff/Complaints/Edit.cshtml
- src/WebApp/Pages/Staff/Complaints/RequestReview.cshtml
- src/WebApp/Pages/Staff/Complaints/Return.cshtml
- src/WebApp/wwwroot/css/site.css
This pull request adds icons to all the alert messages in the application.
> Adding Icons to Alert Messages

- src/Domain/DataViews/DataArchiveViews/RecordsCount.cs
- src/LocalRepository/Repositories/LocalDataViewRepository.cs
- src/WebApp/Pages/Admin/Reporting/Export.cshtml
- src/WebApp/Pages/Public/Index.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/County.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/DateOnlyOrNotEntered.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/FullStaffView.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/IncompleteAddress.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/LongDateTimeOrNotEntered.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/NameOrPlaceholder.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/PhoneNumber.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/ProbableEmailOrNotEntered.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/ProbableUrlOrNotEntered.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/StringOrPlaceholder.cshtml
- src/WebApp/Pages/Shared/DisplayTemplates/TruncateText.cshtml
- src/WebApp/Pages/Shared/_AlertPartial.cshtml
- src/WebApp/Pages/Staff/ComplaintActions/Index.cshtml
- src/WebApp/Pages/Staff/Complaints/Details.cshtml
- src/WebApp/Pages/Staff/Complaints/Index.cshtml
- src/WebApp/wwwroot/css/site.css
Font weight, callouts, responsive tables, etc.
> Polish layout

- docs/Redirects.md
- src/WebApp/Pages/Index.cshtml.cs
- src/WebApp/Pages/Shared/Components/MainMenu/Default.cshtml
- src/WebApp/Pages/Shared/_AttachmentLinkPartial.cshtml
- src/WebApp/Pages/Staff/Complaints/Attachment.cshtml
- src/WebApp/Pages/Staff/Complaints/Attachment.cshtml.cs
- src/WebApp/Pages/Staff/Complaints/Attachment/Index.cshtml
- src/WebApp/Pages/Staff/Index.cshtml.cs
- src/WebApp/Platform/AppConfiguration/AddActiveUserClaimToPrincipal.cs
- src/WebApp/Platform/AppConfiguration/AuthenticationServices.cs
- src/WebApp/Platform/AppConfiguration/BindingsConfiguration.cs
- src/WebApp/Platform/AppConfiguration/DataPersistence.cs
- src/WebApp/Platform/AppConfiguration/IdentityStores.cs
- src/WebApp/Platform/AppConfiguration/MigratorHostedService.cs
- src/WebApp/Platform/AppConfiguration/SecurityHeaders.cs
- src/WebApp/Platform/AppConfiguration/UrlRedirection.cs
- src/WebApp/Platform/PageModelHelpers/AttachmentFileHandler.cs
- src/WebApp/Program.cs
This PR implements redirects from existing URLs for the previous site according to the site map for the new site.
This PR also fixes a permissions issue on the Staff Dashboard page, improves the nav bar menu layout, and moves the Attachments page to improve routing.
> Implement redirects from former site

- src/AppServices/Attachments/AttachmentService.cs
- src/Domain/Domain.csproj.DotSettings
- src/EmailService/EmailService.cs
- src/EmailService/EmailService.csproj.DotSettings
- src/TestData/TestData.csproj.DotSettings
See [ConfigureAwait analysis | JetBrains Rider Documentation](https://www.jetbrains.com/help/rider/ConfigureAwait_Analysis.html)
> Configure ConfigureAwait analysis

- src/WebApp/Pages/Admin/Maintenance/ActionTypes/Index.cshtml
- src/WebApp/Pages/Admin/Maintenance/Concerns/Index.cshtml
- src/WebApp/Pages/Admin/Maintenance/Offices/Index.cshtml
- src/WebApp/Pages/Admin/Reporting/Index.cshtml
- src/WebApp/Pages/Shared/_Layout.cshtml
- src/WebApp/wwwroot/css/site.css
- src/WebApp/wwwroot/images/app-icons.svg
> Replace additional characters with SVG icons

- src/AppServices/Complaints/QueryDto/ComplaintSearchResultDto.cs
- src/WebApp/Pages/Complaint.cshtml.cs
- src/WebApp/Pages/Shared/_ComplaintSearchResultPartial.cshtml
- src/WebApp/Pages/Shared/_DashboardCardPartial.cshtml
- src/WebApp/Pages/Staff/ComplaintActions/Index.cshtml
- src/WebApp/wwwroot/css/site.css
> Add source location to dashboard cards

- src/WebApp/Pages/Shared/_ComplaintSearchResultPartial.cshtml
- src/WebApp/Pages/Shared/_SortableTableColHead.cshtml
- src/WebApp/wwwroot/css/site.css
Added CSS styling from previous EPD page tables to implement responsive and collapsible tables. Embedded classes in cshtml page from bootstrap and partial elements to increase responsiveness across files.
> 597 implement collapsible tables latest
